---
server: true
markdown: maruku
auto: true
cities:
- caracas
    name: Caracas, Distrito Capital
    latitude: 35.110703
    longitude: -106.609991
- valencia
    name: Valencia, Carabobo
    latitude: 35.110703
    longitude: -106.609991
- san_felipe
    name: San Felipe, Yaracuy
    latitude: 35.110703
    longitude: -106.609991
- puerto_ordaz
    name: Puerto Ordaz, Bolivar
    latitude: 35.110703
    longitude: -106.609991
